apiVersion: batch/v1
kind: Job
metadata:
  name: graph-partition-job
spec:
  template:
    spec:
      containers:
      - name: graph-partition-container
        image: meongju0o0/distdgl-partitioning:latest
        volumeMounts:
        - name: graph-partition-pvc
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: graph-partition-pvc
        persistentVolumeClaim:
          claimName: graph-partition-pvc
