apiVersion: batch/v1
kind: Job
metadata:
  name: graph-partition-job
spec:
  template:
    spec:
      containers:
      - name: graph-partition-container
        image: distdgl-partition-graph
        volumeMounts:
        - name: graph-storage
          mountPath: ~/distdgl-on-docker/data
      restartPolicy: Never
      volumes:
      - name: graph-storage
        persistentVolumeClaim:
          claimName: graph-partition-pvc
