apiVersion: batch/v1
kind: Job
metadata:
  name: graph-partition-job
spec:
  template:
    spec:
      containers:
      - name: graph-partition-container
        image: distdgl-partition-graph
        volumeMounts:
        - name: graph-partition-pvc
          mountPath: /home/meongju0o0/distdgl-on-docker/data
      restartPolicy: Never
      volumes:
      - name: graph-partition-pvc
        persistentVolumeClaim:
          claimName: graph-partition-pvc
