FROM python:3.11.5-bullseye

COPY ./codes/* /workspace/

# Install Python libraries
RUN pip install pip==23.2.1 && \
    pip install torch==2.0.1 --index-url https://download.pytorch.org/whl/cpu && \
    pip install dgl==1.1.1 -f https://data.dgl.ai/wheels/repo.html && \
    pip install ogb==1.3.6

# Install build tools and cmake
RUN set -e && apt update && \
    apt upgrade -y && \
    apt install -y build-essential cmake && \
    apt clean

# Install GKlib
RUN set -e && cd /root && \
    git clone https://github.com/KarypisLab/GKlib.git && \
    cd GKlib && \
    make config && \
    make && \
    make install

# Install ParMETIS
RUN set -e && cd /root && \
    git clone https://github.com/KarypisLab/METIS.git && \
    cd METIS && \
    make config shared=1 cc=gcc prefix=/root/local i64=1 && \
    make install

# Change directory to workspace
RUN cd /workspace

# Set Environment Variables
ENV PATH="${PATH}:/root/local/bin"
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/root/local/lib"

CMD ["python3" ,"/workspace/codes/launch.py" ,"--num_trainers", "4", "--num_samplers", "0", "--num_servers", "1", "--part_config", "data/ogbn-products.json", "--ip_config", "ip_config.txt", ""python3 node_classification.py --graph_name ogbn-products --ip_config ip_config.txt --num_epochs 30 --batch_size 1000""]
