apiVersion: v1
kind: PersistentVolume
metadata:
  name: partitioned-graph-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: localhost
    path: ~/distdgl-on-docker/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: partitioned-graph-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: partitioned-graph-pv
