apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: training
spec:
  serviceName: "training-service"
  replicas: 3
  selector:
    matchLabels:
      app: graph-train
  template:
    metadata:
      labels:
        app: graph-train
    spec:
      containers:
      - name: graph-train-container
        image: distdgl-train-graph
        volumeMounts:
        - name: graph-partition-storage
          mountPath: ~/distdgl-on-docker/data
      volumes:
      - name: graph-partition-storage
        persistentVolumeClaim:
          claimName: graph-partition-pvc
