apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
spec:
  completions: 4
  parallelism: 4
  template:
    metadata:
      labels:
        app: graph-train
    spec:
      containers:
      - name: graph-train-container
        image: distdgl-train-graph
        volumeMounts:
        - name: graph-partition-pvc
          mountPath: /home/meongju0o0/distdgl-on-docker/data
      volumes:
      - name: graph-partition-pvc
        persistentVolumeClaim:
          claimName: graph-partition-pvc
      restartPolicy: OnFailure
