FROM python:3.11.5-busseye

COPY ../codes /workspace

# install python libraries
RUN pip install pip==23.2.1 && \
    pip install torch==2.0.1 --index-url https://download.pytorch.org/whl/cpu && \
    pip install dgl==1.1.1 -f https://data.dgl.ai/wheels/repo.html && \
    pip install ogb==1.3.6

# install cmake
RUN apt update && \
    apt upgrade && \
    apt install build-essential && \
    apt install cmake

# install GKlib
RUN cd ~ && \
    git clone https://github.com/KarypisLab/GKlib.git && \
    cd GKlib && \
    make config && \
    make && \
    make install && \
    cd ~

# install ParMETIS
RUN git clone https://github.com/KarypisLab/METIS.git && \
    cd METIS && \
    make config shared=1 cc=gcc prefix=~/local i64=1 $$ \
    make install && \
    export PATH=$PATH:~/local/bin && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/local/lib

CMD ["python3"]
